type = "service_account"
project_id = "wagon-bootcamp-428814"
private_key_id = "e6cd53507f70a8ef25fe98d8ad286f0066bec770"
private_key = '''-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCZSzFwzq17nqaN
XZJAl8Oma7FCQUKjmmzNC2z7sMqAr4rOGX8MyDszXSvNc5dQv0VAyUieks4flf1L
ccwUApOZkD/1V647SMs7D+K7a18S48I9HgdeqCgFZCi2dMVEW8LaZ13i2qfg6Uaj
ddTUyLbK85FdSYm9QmBlbODp/jdecHdwp6WkAtMiKAoGf0/L2YWCYmKHgQWXUgKM
i1UU9YcbgLRsSKt+w8x7UErOL3OkQspjWHGx0ic0YSDJAu1WrGzpH94d7kKux5QW
Xg4T5UbQU7UVEfxH/z1ivPIdkoxcznYUaWNT99E6EHa2yOeeomYIvzrauJJ/9GbA
TOudJ4DBAgMBAAECggEABw18Lm7gpGz3YYGjybz+j2WQN9AkB/FO5PaMAquh/xGu
FsiT6jtvUQmniw6wyevcfJwsiL8p8WIUaUHIqRMFRdQ3kErpOGkJw9as3WdibgGn
w7Z7ketPcnZzn3fEq6rdG1dHubj9oedmcv001/InSgCyxQWUUYgAQpC9a4aUQ/Zh
prZ398K/aWjhCLmqoivJ8KACIw+KV9tQg4T7mZkwz7jPgbDvTsCFnHfQ8J+zPsrK
MjmNinJcpM173k7zP6jlAdf4wWO1m+NKfh5KVt/NskigaFvfV3zZ+4Zpn7w0XD7K
17xoUOPqsRgQgo19Opyg3QzufsIasYOSwJIbxItXwQKBgQDJ13Jx0sejrjC+71O6
egbDy6VRX3rstwvM81Wi82DyMhFsgVDdo1JWQj8bBvOFhxN/xVl5L5gAohsiGvTv
AC8LI1OTqlPRHu6BtrxmK39TFthvAgdz33eXFl7C1rhX/SV5/MyhG+U9CdAL/HBj
VQE7UdtVgaIgf0YqcrKelHO8JQKBgQDCbPrmq/ucuhry7TyM6Th+xmYp0sZEQwdZ
fh4QzL726hyvSYvtIM58HbWB7VoqsWwztYS65ysUx1gSvBQ++3YgIXptYk++9bkm
W+Ws5zKN3gfH28vdozLTTInC5NIdGyFaW5k458S1C4sQPJZYQ+b3xAz1rP0w1Fap
K7RJWD9BbQKBgCpy9C+6C6CB5uCRBsPmG/wbnSYS9ZBJIuM0neMKWm41V3LBc5dZ
XNylTA5MFPUVJmWtxJZ3Cvm/HgO7NZ36JOqrwE0C+mO1pKWFH/RA26NG37fg7l5R
Nh6BZuaFL/nZVINmRkbvzfNbV/TdX2mUnBC0s3M1MzqwabpNqwEs6XY9AoGAAzW9
ZrWML+g6rawRBdqL3jv0T9h1AYeBxY55fJmExZrT4mj6cG3MOuxapMyAYpgPS0NB
77wFUBCCeby1MN0B9EHZPZkT6/kul12JCzO99+2kfz43vW8GVcq7s4YHmgdqo41D
mFbrPnn0T85QRSDJ3WlVNXEntPisfZqFHXjhgnkCgYAHfEkG/UAozazU+ICYe/Ps
4fZpsL6hPDRHS46Hl719wdLJpGb823IPjHujucTyK3SsWjYU9imBZ3rdLDIWBy31
PeJgb+MjuZqXD+zUghdlQTJWM8sug/L85xAk+PjYLG3LVfxw23onIlbSNtC8CaNq
ySLym8Mg1CnqTK1ah6HWkg==
-----END PRIVATE KEY-----'''
client_email = "le-wagon-service-account@wagon-bootcamp-428814.iam.gserviceaccount.com"
client_id = "103501298538594605802"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/le-wagon-service-account%40wagon-bootcamp-428814.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
